import Head from 'next/head'
import Message from '@/components/message'
import { useState, useEffect } from 'react'
import Link from "next/link";
import {db} from '../utils/firebase'
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";


export default function Home() {
  
  //Create a state with all the posts
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  }, []);
  
  return (
    <div>
      <Head>
        <title>Body Mind Fitness</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/bbmfc.png" />
      </Head>
      <main></main>
      <div className='my-12'>
      <h2 className='heading1 font-popin text-3xl mb-4 decoration-solid'>See the latest updates and connect with Deepak Sir here!!</h2>
      
      {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
              <button>
                {post.comments?.length > 0 ? post.comments?.length : 0} comments
              </button>
            </Link>
          </Message>
        ))}
      </div>
    </div>
  )
}
